### ISSUE TITLE
Why does csscomp have vendorprefixing for opera only?

### ISSUE THREAD

**Issue by bogusred** [google/generator-goro#7]
https://github.com/google/generator-goro/blob/master/app/templates/css/_default.min.css#L17

Is there a particular reason we restrict this to opera only? It seems like we should use webkit at least.

**Comment by anthonyhastings** [comment]
https://help.googlegoro.com/docs/1341012532686/template-tags.html#csscomp

The dash at the start of vendors is to exclude vendors, so autoprefixer is targeting everything apart from opera.

**Comment by bogusred** [comment]
Thank you Anthony. I misunderstood that. I guess we don't need the opera prefix anymore because opera reads the webkit prefixes or the standards now?

**Comment by anthonyhastings** [comment]
Exactly. Opera now uses blink as its rendering engine.

**Comment by bogusred** [comment]
Got it. thank you and Merry Christmas Eve.

**Comment by anthonyhastings** [comment]
You're very welcome! Merry Christmas!
